default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  host: localhost
  database: air-monitor_production
  username: air-monitor
  password: <%= ENV['AIRMONITOR_DATABASE_PASSWORD'] %>
