default: &default
  adapter: postgresql
  host: db # Docker
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: AirMonitor_development
  username: postgres
  password:

test:
  <<: *default
  database: AirMonitor_test
  username: postgres
  password:
