default: &default
  adapter: postgresql
  host: db
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: AirMonitor_development
  username: postgres
  password:

test:
  <<: *default
  database: AirMonitor_test
  username: postgres
  password:

production:
  <<: *default
  database: air-monitor_production
  username: air-monitor
  password: <%= ENV['AIRMONITOR_DATABASE_PASSWORD'] %>
