default: &default
  adapter: postgresql
  host: db
  encoding: unicode
  pool: 5

production:
  <<: *default
  database: air-monitor_production
  username: <%= ENV['AIRMONITOR_DATABASE_USERNAME'] %>
  password: <%= ENV['AIRMONITOR_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: AirMonitor_development
  username: postgres
  password:

test:
  <<: *default
  database: AirMonitor_test
  username: postgres
  password:
